import { existsSync, writeFileSync } from 'node:fs';
import { askYesNo, printStep, printSuccess, printWarning, printInfo } from '../prompts.js';
import { SPECIALIST_TEMPLATES, ROUTER_CATEGORIES } from '../defaults.js';
import { contextSizeForTier } from '../measured-models.js';
import type { OllamaStepResult } from './ollama.js';
import type { ModelsStepResult } from './models.js';
import type { ChannelsStepResult } from './channels.js';
import type { ServicesStepResult } from './services.js';

export interface GenerateStepResult {
  envPath: string;
  configPath: string;
}

export interface WizardState {
  ollama: OllamaStepResult;
  models: ModelsStepResult;
  channels: ChannelsStepResult;
  services: ServicesStepResult;
}

export function buildEnv(state: WizardState): string {
  const lines: string[] = ['# Generated by Invarail setup wizard', ''];

  // Ollama
  lines.push('# Ollama');
  lines.push(`OLLAMA_URL=${state.ollama.url}`);
  lines.push('');

  // Web console token (only when exposed beyond loopback)
  if (state.channels.web.enabled && state.channels.web.token) {
    lines.push('# Web console bearer token — paste into the console Login page and the extension settings');
    lines.push(`WEB_TOKEN=${state.channels.web.token}`);
    lines.push('');
  }

  // Discord
  if (state.channels.discord.enabled && state.channels.discord.token) {
    lines.push('# Discord');
    lines.push(`DISCORD_BOT_TOKEN=${state.channels.discord.token}`);
    lines.push('');
  }

  // Telegram
  if (state.channels.telegram.enabled && state.channels.telegram.token) {
    lines.push('# Telegram');
    lines.push(`TELEGRAM_BOT_TOKEN=${state.channels.telegram.token}`);
    lines.push('');
  }

  // Web search API key (hosted providers only)
  if (state.services.webSearch.enabled && state.services.webSearch.provider !== 'searxng' && state.services.webSearch.apiKey) {
    const provider = state.services.webSearch.provider ?? 'brave';
    const envVar = `${provider.toUpperCase()}_API_KEY`;
    lines.push('# Web Search');
    lines.push(`${envVar}=${state.services.webSearch.apiKey}`);
    lines.push('');
  }

  // TTS
  if (state.services.tts.enabled && state.services.tts.url) {
    lines.push('# TTS');
    lines.push(`QWEN_TTS_URL=${state.services.tts.url}`);
    lines.push('');
  }

  // STT
  if (state.services.stt.enabled && state.services.stt.url) {
    lines.push('# STT');
    lines.push(`WHISPER_URL=${state.services.stt.url}`);
    lines.push('');
  }

  // Image generation
  if (state.services.imageGen.enabled && state.services.imageGen.url) {
    lines.push('# Image Generation');
    lines.push(`IMAGE_GEN_URL=${state.services.imageGen.url}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Determine which specialist categories to include based on enabled services.
 */
function getEnabledCategories(state: WizardState): Set<string> {
  const enabled = new Set(['chat', 'memory', 'exec', 'task', 'multi', 'cron']);

  if (state.services.webSearch.enabled || state.services.browser.enabled) {
    enabled.add('web_search');
    enabled.add('website');
    enabled.add('research');
  }

  const hasChannels = state.channels.discord.enabled
    || state.channels.telegram.enabled;
  if (hasChannels) {
    enabled.add('message');
  }

  if (state.services.imageGen.enabled) {
    enabled.add('image');
  }

  if (state.services.pi.enabled) {
    enabled.add('code_gen');
  }

  return enabled;
}

export function buildConfig(state: WizardState): string {
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const defaultModel = state.models.specialistModel;
  // ONE context size for every call that lands on the foreground model. Ollama treats a
  // num_ctx change as a reload: with the router at 8K, extraction at 8K and chat at 32K on
  // the same model, a one-model install reloaded it on every hop and the router timed out
  // on every message (e2e eval 2026-09-27 — 100% keyword fallback).
  const tier = state.models.foregroundTier ?? 'full';
  const contextSize = contextSizeForTier(tier);
  const enabledCategories = getEnabledCategories(state);

  // Owner ID
  const ownerIdLine = state.channels.ownerId
    ? `  ownerId: "${state.channels.ownerId}",`
    : `  // ownerId: "your-user-id",  // Set this to gate owner-only tools (gmail, calendar)`;

  // Build specialists block
  const specialistLines: string[] = [];
  for (const [category, template] of Object.entries(SPECIALIST_TEMPLATES)) {
    if (!enabledCategories.has(category)) continue;
    const model = state.models.categoryModels[category] ?? defaultModel;
    const thinkLine = model === defaultModel && state.models.specialistThink !== undefined
      ? `\n      think: ${state.models.specialistThink},   // the mode that scored best for this model in the evals`
      : '';
    const sp = template.systemPrompt
      ? `\n      systemPrompt: ${JSON.stringify(template.systemPrompt)},`
      : '';
    const toolsStr = template.tools.length
      ? `[${template.tools.map(t => `"${t}"`).join(', ')}]`
      : '[]';
    const pipelineLine = template.pipeline
      ? `\n      pipeline: "${template.pipeline}",`
      : '';
    const modeLine = template.dispatchMode
      ? `\n      dispatchMode: "${template.dispatchMode}",`
      : '';

    specialistLines.push(`    ${category}: {
      model: "${model}",${thinkLine}${sp}
      maxTokens: ${template.maxTokens},
      temperature: ${template.temperature},
      maxIterations: ${template.maxIterations},
      tools: ${toolsStr},${pipelineLine}${modeLine}
    },`);
  }

  // Build router categories block
  const categoryLines: string[] = [];
  for (const [name, cat] of Object.entries(ROUTER_CATEGORIES)) {
    if (!enabledCategories.has(name)) continue;
    categoryLines.push(`      ${name}: { description: "${cat.description}" },`);
  }

  // Build channels block with security
  const channelLines: string[] = [];
  const channelEntries: Array<{ name: string; result: { enabled: boolean; token?: string; port?: number; host?: string } }> = [
    { name: 'discord', result: state.channels.discord },
    { name: 'telegram', result: state.channels.telegram },
    { name: 'web', result: state.channels.web },
  ];

  for (const ch of channelEntries) {
    if (!ch.result.enabled) {
      channelLines.push(`    ${ch.name}: { enabled: false },`);
      continue;
    }

    const parts: string[] = [`      enabled: true,`];

    // Token
    if (ch.name === 'discord' && ch.result.token) parts.push(`      token: "\${DISCORD_BOT_TOKEN}",`);
    if (ch.name === 'telegram' && ch.result.token) parts.push(`      token: "\${TELEGRAM_BOT_TOKEN}",`);
    if (ch.name === 'web') {
      parts.push(`      port: ${ch.result.port ?? 3100},`);
      parts.push(`      host: "${ch.result.host ?? '127.0.0.1'}",`);
      if (ch.result.token) parts.push(`      token: "\${WEB_TOKEN}",   // generated by setup; the adapter refuses a network bind without one`);
    }

    // Security block
    const trusted = state.channels.trustedUsers[ch.name];
    if (trusted && trusted.length > 0) {
      parts.push(`      security: {`);
      parts.push(`        trustedUsers: [${trusted.map(id => `"${id}"`).join(', ')}],`);
      parts.push(`        restrictedCategories: ["exec"],`);
      if (state.channels.ownerId) {
        parts.push(`        ownerOnlyTools: ["gmail_search", "gmail_read", "calendar_list", "calendar_search"],`);
      }
      parts.push(`      },`);
    }

    channelLines.push(`    ${ch.name}: {\n${parts.join('\n')}\n    },`);
  }

  // Web search config
  let webSearchBlock = '';
  if (state.services.webSearch.enabled) {
    const ws = state.services.webSearch;
    const provider = ws.provider ?? 'brave';
    const ceiling = ws.dailyQueryCeiling ?? 250;
    if (provider === 'searxng') {
      webSearchBlock = `
      search: {
        provider: "searxng",
        baseUrl: "${ws.baseUrl ?? 'http://localhost:8080'}",
        dailyQueryCeiling: ${ceiling},   // outbound queries per day — a metasearch spends YOUR IP's reputation (SEARXNG.md)
      },`;
    } else {
      const envVar = `${provider.toUpperCase()}_API_KEY`;
      webSearchBlock = `
      search: {
        provider: "${provider}",
        apiKey: "\${${envVar}}",
        dailyQueryCeiling: ${ceiling},
      },`;
    }
  }

  // Exec block
  const execSecurity = state.services.exec.security;
  const execBlock = `    exec: {
      security: "${execSecurity}",
      allowlist: ["ls", "cat", "python3", "node", "git"],
      timeout: 30000,
    },`;

  // TTS block
  let ttsBlock = `  tts: { enabled: false },`;
  if (state.services.tts.enabled) {
    ttsBlock = `  tts: {
    enabled: true,
    url: "\${QWEN_TTS_URL}",
    voice: "serena",
    format: "opus",
  },`;
  }

  // STT block
  let sttBlock = `  stt: { enabled: false },`;
  if (state.services.stt.enabled) {
    sttBlock = `  stt: {
    enabled: true,
    url: "\${WHISPER_URL}",
    model: "whisper-large-v3",
    language: "en",
  },`;
  }

  // Vision block
  let visionBlock = `  vision: { enabled: false },`;
  if (state.services.vision.enabled) {
    const vModel = state.services.vision.model ?? 'qwen3-vl:8b';
    visionBlock = `  vision: {
    enabled: true,
    model: "${vModel}",
    prompt: "Describe this image in detail. Include text content, visual elements, layout, and any relevant context. /no_think",
    maxTokens: 1024,
  },`;
  }

  // Browser block
  let browserBlock = `  browser: { enabled: false },`;
  if (state.services.browser.enabled) {
    browserBlock = `  browser: {
    enabled: true,
    headless: ${state.services.browser.headless},
  },`;
  }

  // Heartbeat block — omitted when disabled: the schema requires `delivery` whenever the
  // block exists, so `heartbeat: { enabled: false }` never parsed (round-trip test, 2026-09-27).
  let heartbeatBlock = '';
  if (state.services.heartbeat.enabled && state.services.heartbeat.channel) {
    heartbeatBlock = `  heartbeat: {
    enabled: true,
    schedule: "0 */2 * * *",
    model: "${state.models.backgroundModel}",
    delivery: {
      channel: "${state.services.heartbeat.channel}",
      target: "${state.services.heartbeat.target ?? ''}",
    },
  },`;
  }

  // Inference backends (OpenAI-compatible, e.g. vLLM) + briefing model
  const inferenceBlock = state.models.inferenceBackends.length
    ? `  inference: {
    backends: [
${state.models.inferenceBackends.map(b => `      { url: "${b.url}", models: [${b.models.map(m => `"${m}"`).join(', ')}] },`).join('\n')}
    ],
  },
`
    : '';
  const briefingBlock = `  briefing: { model: "${state.models.backgroundModel}" },`;

  // Reasoning block
  let reasoningBlock = '';
  if (state.services.reasoning.enabled && state.services.reasoning.model) {
    reasoningBlock = `
  reasoning: {
    model: "${state.services.reasoning.model}",
    maxTokens: 8192,
    temperature: 0.6,
  },`;
  }

  // Image gen block
  let imageGenBlock = '';
  if (state.services.imageGen.enabled) {
    imageGenBlock = `
  imageGen: {
    enabled: true,
    url: "\${IMAGE_GEN_URL}",
    model: "${state.services.imageGen.model ?? 'flux2-klein:4b-fp8'}",
  },`;
  }

  // Pi coding agent block
  let piBlock = '';
  if (state.services.pi.enabled) {
    piBlock = `
  pi: {
    enabled: true,
    model: "${state.services.pi.model ?? 'vllm/deepseek-v4-flash'}",
  },`;
  }

  // Voice block — the foreground model, not the router: a small model beside a big one
  // splits to CPU and is SLOWER (DECISIONS, voice round three).
  let voiceBlock = '';
  if (state.services.tts.enabled) {
    voiceBlock = `
  voice: {
    model: "${defaultModel}",
    maxTokens: 160,
  },`;
  }

  // Memory block
  const mem = state.services.memory ?? { backend: 'flat' as const, embeddingModel: 'none' };
  const memoryBlock = `  memory: {
    // Memory tier (src/memory/policy.ts): graph = FalkorDB + embeddings; flat = JSONL facts,
    // keyword recall; vault = flat facts + your markdown folder, exact-word search.
    backend: "${mem.backend}",
    embeddingModel: "${mem.embeddingModel}",${mem.embeddingModel === 'none' ? '   // no embedder: nothing dense, nothing to fit beside the chat model' : ''}
    extractionModel: "${defaultModel}",
    extractionContextSize: ${contextSize},   // same num_ctx as the specialists — one load, no reload per capture
    consolidation: {
      enabled: ${mem.embeddingModel !== 'none'},
      model: "${state.models.routerModel}",
      similarityThreshold: 0.85,
    },
  },
  vault: {
    path: "${mem.vaultPath ?? 'vault'}",${mem.okf ? `
    okf: true,   // Open Knowledge Format: front matter, facts as notes, index.md / log.md the model navigates` : ''}
  },`;

  return `{
  // Invarail Configuration
  // Generated by setup wizard

  // THE foreground model — filled into every specialist/briefing/heartbeat/vision slot
  // that does not set its own. A model change is this one line.
  defaultModel: "${defaultModel}",
  // Prompt profile for that model's tier (evals/2026-09-e2e): small = minimal workspace set
  // for chat + 4K-char file cap + 16K context. Change the model, re-run \`npm run doctor\`.
  promptProfile: "${tier}",
${ownerIdLine}
  timezone: "${tz}",

  ollama: {
    url: "\${OLLAMA_URL}",
    keepAlive: "30m",
    // Every call that does not name a num_ctx (quality judge, summaries) gets THIS one, so
    // nothing loads the model at a second context size (A/B run 2026-09-27: a 16K install
    // ping-ponged against the server's 32K default — 6 router timeouts, 5s reloads).
    defaultContextSize: ${contextSize},
  },

${inferenceBlock}${briefingBlock}

  router: {
    model: "${state.models.routerModel}",
    timeout: 2000,${state.models.routerModel === defaultModel
      ? `\n    contextSize: ${contextSize},   // the router IS the foreground model: a different num_ctx would reload it on every turn (e2e eval 2026-09-27)`
      : ''}
    defaultCategory: "chat",
    categories: {
${categoryLines.join('\n')}
    },
  },

  specialists: {
${specialistLines.join('\n')}
  },

  channels: {
${channelLines.join('\n')}
  },

  agents: {
    default: "main",
    list: [
      { id: "main", name: "Invarail Assistant" },
    ],
    bindings: [],
  },

${memoryBlock}

  cron: { enabled: true, store: "data/cron.json" },

  session: {
    transcriptDir: "data/sessions",
    maxHistoryTurns: 100,
    contextSize: ${contextSize},
    recentTurnsToKeep: 6,
    summarizeToolObservations: true,
  },

  tools: {
    web: {${webSearchBlock}
      fetch: { maxChars: 30000 },
    },
${execBlock}
  },

  ${heartbeatBlock}

  ${browserBlock}

  ${ttsBlock}

  ${sttBlock}

  ${visionBlock}${reasoningBlock}${imageGenBlock}${piBlock}${voiceBlock}
}
`;
}

export async function runGenerateStep(state: WizardState): Promise<GenerateStepResult> {
  printStep(6, 7, 'Generate Configuration');

  const envContent = buildEnv(state);
  const configContent = buildConfig(state);

  let envPath = '.env';
  let configPath = 'invarail.config.json5';

  // Check for existing files
  if (existsSync(envPath)) {
    printWarning('.env already exists');
    const overwrite = await askYesNo('Overwrite .env?', false);
    if (!overwrite) {
      envPath = '.env.setup';
      printInfo(`Writing to ${envPath} instead`);
    }
  }

  if (existsSync(configPath)) {
    printWarning('invarail.config.json5 already exists');
    const overwrite = await askYesNo('Overwrite invarail.config.json5?', false);
    if (!overwrite) {
      configPath = 'invarail.config.json5.setup';
      printInfo(`Writing to ${configPath} instead`);
    }
  }

  writeFileSync(envPath, envContent, 'utf-8');
  printSuccess(`Written: ${envPath}`);

  writeFileSync(configPath, configContent, 'utf-8');
  printSuccess(`Written: ${configPath}`);

  return { envPath, configPath };
}
