import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { askChoice, askYesNo, printHeader, printInfo, printSuccess, printWarning } from '../prompts.js';
import { rankForeground, memoryBudgetGb, findMeasured } from './../measured-models.js';
import type { OllamaModel } from '../../ollama/types.js';
import type { DetectReport } from '../detect.js';

export type SetupTier = 'starter' | 'custom';

/** First wizard question: how much system do you want? */
export async function runTierStep(): Promise<SetupTier> {
  printHeader('Setup style');
  printInfo('Starter — one model, web console only, nothing else to install (~15 min)');
  printInfo('Custom  — pick channels, models, and services yourself (full wizard)\n');
  const choice = await askChoice('How do you want to run Invarail?', ['Starter', 'Custom']);
  return choice.toLowerCase() as SetupTier;
}

/**
 * Starter short-circuit: verify Ollama, pick ONE model for every slot, write
 * the preset. The preset file is the source of truth — this only swaps the
 * model name, so preset and wizard can never drift apart.
 */
export async function runStarterGenerate(models: OllamaModel[], report?: DetectReport): Promise<void> {
  const ranked = rankForeground(models, memoryBudgetGb(report?.memory));
  let model = 'qwen3.5:9b';
  if (ranked.length > 0) {
    const labels = ranked.map(r => r.label);
    const chosen = await askChoice('Which model should do everything? (ranked by the evals and by fit)', labels);
    model = ranked[Math.max(0, labels.indexOf(chosen))].name;
  }
  if (models.length === 0) {
    printWarning('No models found in Ollama — defaulting to qwen3.5:9b (the measured floor for tool use). Pull it with: ollama pull qwen3.5:9b');
  }

  // Module-relative: `npm run setup` runs at the repo root, but the wizard must not depend on cwd
  // (headless smoke from a scratch dir failed with ENOENT, 2026-09-27).
  let template = readFileSync(resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'invarail.config.starter.json5'), 'utf-8');
  template = template.replaceAll('qwen3.5:9b', model);
  // The preset says think: false (right for the measured floor). A measured model whose
  // best mode was thinking ON keeps it; an unmeasured model keeps the engine default.
  const m = findMeasured(model);
  if (m && m.think !== 'off' && m.think !== 'none') template = template.replace(/^(\s*)think: false,.*$/m, '$1think: true,   // the mode that scored best for this model in the evals');
  else if (!m) template = template.replace(/^\s*think: false,.*\n/m, '');

  // Exposure is a choice; the token comes with it (see channels step for why).
  if (await askYesNo('Reach the console from OTHER devices on your network (phone, the Chrome extension)?', false)) {
    const token = randomBytes(32).toString('hex');
    template = template.replace(/^(\s*)host: "127\.0\.0\.1",.*$/m, '$1host: "0.0.0.0",\n$1token: "${WEB_TOKEN}",   // generated by setup — paste into the console Login page / extension settings');
    appendFileSync('.env', `\n# Web console bearer token (generated by setup ${new Date().toISOString().slice(0, 10)})\nWEB_TOKEN=${token}\n`);
    printSuccess('Console exposed to the LAN with a generated bearer token (WEB_TOKEN in .env)');
  }

  let configPath = 'invarail.config.json5';
  if (existsSync(configPath)) {
    printWarning('invarail.config.json5 already exists');
    const overwrite = await askYesNo('Overwrite invarail.config.json5?', false);
    if (!overwrite) configPath = 'invarail.config.json5.starter';
  }
  writeFileSync(configPath, template, 'utf-8');

  printSuccess(`Wrote ${configPath} (model: ${model})`);
  printInfo('\nNext steps:');
  printInfo('  npm start          → open http://localhost:3100');
  printInfo('  INSTALL.md         → the upgrade ladder (search, channels, memory graph, exec)');
  printInfo('  docker compose up  → graph memory + web search sidecars (Tier 1)');
}
